src/Entity/Offre.php
<?php

namespace App\Entity;

use App\Repository\OffreRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: OffreRepository::class)]
class Offre
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $dateCandidature = null;

    #[ORM\Column(length: 255)]
    private ?string $entreprise = null;

    #[ORM\Column(length: 255)]
    private ?string $lieu = null;

    #[ORM\Column(length: 255)]
    private ?string $url = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $contact = null;



    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $reponse_at = null;


    #[ORM\Column(length: 255)]
    private ?string $type = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $relance_at = null;

    #[ORM\Column]
    private ?bool $freelance = null;

    #[ORM\Column(length: 255)]
    private ?string $description = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $relance = null;

    #[ORM\Column(length: 5, nullable: true)]
    private ?string $reponse = null;

    #[ORM\Column(length: 5, nullable: true)]
    private ?string $lettre_motivation = null;

    /**
     * @var bool|null
     */
    private ?bool $isUrlValid = null;

    public function setIsUrlValid(bool $isUrlValid): self
    {
        $this->isUrlValid = $isUrlValid;
        return $this;
    }

    public function getIsUrlValid(): ?bool
    {
        return $this->isUrlValid;
    }
    public function __construct()
    {
        $this->type = 'Informatique';
    }
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateCandidature(): ?\DateTimeInterface
    {
        return $this->dateCandidature;
    }

    public function setDateCandidature(\DateTimeInterface $dateCandidature): static
    {
        $this->dateCandidature = $dateCandidature;

        return $this;
    }

    public function getEntreprise(): ?string
    {
        return $this->entreprise;
    }

    public function setEntreprise(string $entreprise): static
    {
        $this->entreprise = $entreprise;

        return $this;
    }

    public function getLieu(): ?string
    {
        return $this->lieu;
    }

    public function setLieu(string $lieu): static
    {
        $this->lieu = $lieu;

        return $this;
    }

    public function getUrl(): ?string
    {
        return $this->url;
    }
    public function getSiteNameFromUrl(): ?string
    {
        if (!$this->url) {
            return null;
        }

        $parsedUrl = parse_url($this->url);
        $host = $parsedUrl['host'] ?? null;

        if ($host) {
            // Supprime "www." au début et l'extension (.fr, .com, etc.) à la fin
            $host = preg_replace('/^www\./', '', $host); // Enlève "www."
            $host = preg_replace('/\.[a-z]{2,}$/', '', $host); // Enlève l'extension
        }

        return $host;
    }




    public function setUrl(string $url): static
    {
        $this->url = $url;

        return $this;
    }

    public function getContact(): ?string
    {
        return $this->contact;
    }

    public function setContact(?string $contact): static
    {
        $this->contact = $contact;

        return $this;
    }



    public function getReponseAt(): ?\DateTimeInterface
    {
        return $this->reponse_at;
    }

    public function setReponseAt(?\DateTimeInterface $reponse_at): static
    {
        $this->reponse_at = $reponse_at;

        return $this;
    }



    public function getType(): ?string
    {
        return $this->type ? $this->type : 'Informatique';
    }

    public function setType(string $type): static
    {
        $this->type = $type;

        return $this;
    }

    public function getRelanceAt(): ?\DateTimeInterface
    {
        return $this->relance_at;
    }

    public function setRelanceAt(?\DateTimeInterface $relance_at): static
    {
        $this->relance_at = $relance_at;

        return $this;
    }

    public function isFreelance(): ?bool
    {
        return $this->freelance;
    }

    public function setFreelance(bool $freelance): static
    {
        $this->freelance = $freelance;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getRelance(): ?string
    {
        return $this->relance;
    }

    public function setRelance(?string $relance): static
    {
        $this->relance = $relance;

        return $this;
    }

    public function getReponse(): ?string
    {
        return $this->reponse;
    }

    public function setReponse(?string $reponse): static
    {
        $this->reponse = $reponse;

        return $this;
    }

    public function getLettreMotivation(): ?string
    {
        return $this->lettre_motivation;
    }

    public function setLettreMotivation(?string $lettre_motivation): static
    {
        $this->lettre_motivation = $lettre_motivation;

        return $this;
    }
}

src/Form/OffreType.php
<?php

namespace App\Form;

use App\Entity\Offre;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\UrlType;

use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\FormEvents;

class OffreType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder

            ->add('description', TextType::class, [
                'label' => 'Poste',
                'attr' => ['class' => 'form-control', 'placeholder' => 'Poste'],
            ])
            ->add('dateCandidature', DateType::class, [
                'widget' => 'single_text',
                'label' => 'Date de candidature',
                'attr' => ['class' => 'form-control'],
            ])
            ->add('entreprise', TextType::class, [
                'label' => 'Nom de l\'entreprise',
                'attr' => ['class' => 'form-control', 'placeholder' => 'Nom de l\'entreprise'],
            ])
            ->add('lieu', TextType::class, [
                'label' => 'Lieu',
                'attr' => ['class' => 'form-control', 'placeholder' => 'Ville ou adresse'],
            ])
            ->add('url', UrlType::class, [
                'label' => 'Lien vers l\'offre',
                'attr' => ['class' => 'form-control', 'placeholder' => 'https://'],
            ])
            ->add('contact', TextareaType::class, [
                'label' => 'Contact',
                'required' => false,
                'attr' => ['class' => 'form-control'],
            ])
            ->add('type', ChoiceType::class, [
                'label' => 'Type',
                'choices' => [
                    'Informatique' => 'Informatique',
                    'Autre' => 'Autre',
                ],
                'expanded' => true,
                'multiple' => false,
                'choice_attr' => function () {
                    return ['class' => 'form-check-input'];
                },
                'label_attr' => ['class' => 'form-check-label'],
                'row_attr' => ['class' => 'form-check form-check-inline'],
                'data' => 'Informatique',
                'label_html' => true,
                'choice_label' => function ($choice, $key, $value) {
                    return sprintf('<span class="form-option-text">%s</span>', $choice);
                }
            ])
            ->add('reponse', ChoiceType::class, [
                'label' => 'Réponse',
                'choices' => [
                    'en attente'    => 'ATTENTE',
                    'Oui' => 'OUI',
                    'Non' => 'NON',
                ],
                'expanded' => true,
                'data' => 'ATTENTE',
            ])
            ->add('reponse_at', DateType::class, [
                'widget' => 'single_text',
                'label' => 'Date de réponse',
                'required' => false,
                'attr' => ['class' => 'form-control'],
            ])
            ->add('lettre_motivation_checkbox', CheckboxType::class, [
                'label' => 'Lettre de motivation requise',
                'required' => false,
                'mapped' => false,
            ])

            ->add('relance_at', DateType::class, [
                'widget' => 'single_text',
                'label' => 'Date de relance',
                'required' => false,
                'attr' => ['class' => 'form-control'],
            ])
            ->add('freelance', CheckboxType::class, [
                'label' => 'Freelance ?',
                'required' => false,
                'attr' => ['class' => 'form-check-input'],
            ]);
        // Écouteurs d'événements pour gérer la transformation entre checkbox et valeur de chaîne
        $builder->addEventListener(FormEvents::PRE_SET_DATA, function (FormEvent $event) {
            $offre = $event->getData();
            $form = $event->getForm();

            // Si l'offre existe et que la lettre de motivation est "oui", cocher la case
            if ($offre && $offre->getLettreMotivation() === 'oui') {
                $form->get('lettre_motivation_checkbox')->setData(true);
            }
        });

        $builder->addEventListener(FormEvents::POST_SUBMIT, function (FormEvent $event) {
            $form = $event->getForm();
            $offre = $event->getData();

            // Convertir l'état de la checkbox en "oui" ou "non"
            $checked = $form->get('lettre_motivation_checkbox')->getData();
            $offre->setLettreMotivation($checked ? 'oui' : 'non');
        });
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Offre::class,
        ]);
    }
}

src/Controller/OffreController.php
<?php

namespace App\Controller;

use App\Entity\Offre;
use Twig\Environment;
use App\Form\OffreType;
use App\Service\UrlCheckerService;
use App\Repository\OffreRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

#[Route('/admin')]
final class OffreController extends AbstractController
{
    public function __construct(
        private OffreRepository $offreRepository,
        private UrlCheckerService $urlChecker
    ) {}

    #[Route('/{filter<NON|ATT>?}', name: 'app_home', methods: ['GET'])]
    #[Route('/{checkUrls<1>?}', name: 'app_home', methods: ['GET'])]
    public function index(?string $filter = null, ?int $checkUrls = null): Response
    {
        $offres = $this->getFilteredOffres($filter);

        if ($checkUrls) {
            $this->validateOffresUrls($offres);
        }
        return $this->render('offre/index.html.twig', [
            'offres' => $offres,
        ]);
    }

    private function getFilteredOffres(?string $filter): array
    {
        return match ($filter) {
            'ATT' => $this->offreRepository->findBy(
                ['reponse' => ['ATT', '']],
                ['id' => 'DESC']
            ),
            'NON' => $this->offreRepository->findBy(
                ['reponse' => 'NON'],
                ['id' => 'DESC']
            ),
            default => $this->offreRepository->findBy(
                [],
                ['id' => 'DESC']
            )
        };
    }

    private function validateOffresUrls(array $offres): void
    {
        foreach ($offres as $offre) {

            if ($this->shouldValidateUrl($offre)) {
                $offre->setIsUrlValid($this->urlChecker->isUrlValid($offre->getUrl()));
            }
        }
    }

    private function shouldValidateUrl(Offre $offre): bool
    {

        return $offre->getUrl() && $offre->getReponse() !== 'NON';
    }


    #[Route('/new', name: 'app_offre_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $offre = new Offre();
        $form = $this->createForm(OffreType::class, $offre);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($offre);
            $entityManager->flush();

            return $this->redirectToRoute('app_home', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('offre/new.html.twig', [
            'offre' => $offre,
            'form' => $form,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_offre_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Offre $offre, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(OffreType::class, $offre);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_home', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('offre/edit.html.twig', [
            'offre' => $offre,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_offre_delete', methods: ['POST'])]
    public function delete(Request $request, Offre $offre, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete' . $offre->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($offre);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_home', [], Response::HTTP_SEE_OTHER);
    }

    #[Route('/find/{find}', name: 'app_offre_find', methods: ['POST'])]
    public function find(string $find, OffreRepository $offreRepository, Environment $twig): Response
    {
        $offres = $offreRepository->findByMotsCles($find);

        return new Response($twig->render('offre/_tbody.html.twig', [
            'offres' => $offres
        ]));
    }
}

templates/offre/_delete_form.html.twig
<form method="post" action="{{ path('app_offre_delete', {'id': offre.id}) }}" onsubmit="return confirm('Etes vous sur de vouloir supprimer cette candidature ?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ offre.id) }}">
    <button class="btn btn-danger mt-5">Supression</button>
</form>

templates/offre/_find.html.twig
<form>

<input type="text" id="search" placeholder="entreprise, lieu, contact" class="form-control" />
</form>


<script>
document.getElementById('search').addEventListener('input', function() {
    let query = this.value.trim();

    if (query.length < 2) { // Évite les requêtes inutiles
        return;
    }

    fetch('/admin/find/' + encodeURIComponent(query), {
        method: 'POST',
        headers: {
            'X-Requested-With': 'XMLHttpRequest' // Pour différencier les requêtes AJAX
        }
    })
    .then(response => response.text()) // Récupère le HTML du serveur
    .then(html => {
        document.querySelector("#myTable tbody").innerHTML = html;
    })
    .catch(error => console.error('Erreur:', error));
});
</script>

templates/offre/_form.html.twig
{% block javascripts %}
    {{ encore_entry_script_tags("importOffre") }}
{% endblock %}
{{ form_start(form) }}
     <div class="row">
        <div class="col-md-4">
            <div class="mb-3 row align-items-center">
                <div class="col-sm-2">
                    {{ form_label(form.type, 'Type', {'label_attr': {'class': 'form-label mb-0'}}) }}
                </div>
                <div class="col-sm-10">
                    <style>
                        .reversed-radio .form-check-label {
                            display: flex;
                            flex-direction: row-reverse;
                            justify-content: flex-end;
                            gap: 0.5rem;
                        }
                        .reversed-radio .form-check-input {
                            margin-top: 0.25rem;
                        }
                    </style>
                    <div class="d-flex reversed-radio">
                        {{ form_widget(form.type, {'attr': {'class': 'form-check-inline'}}) }}
                    </div>
                    {{ form_errors(form.type) }}
                </div>
            </div>            
        </div>
        <div class="col-md-4">
            <div class="mb-3">
                {{ form_label(form.lettre_motivation_checkbox, 'Lettre de motivation', {'label_attr': {'class': 'form-label'}}) }}
                {{ form_widget(form.lettre_motivation_checkbox, {'attr': {'class': 'form-check-input'}}) }}
                {{ form_errors(form.lettre_motivation_checkbox) }}
            </div>
        </div>
        <div class="col-md-4">
            <div class="mb-3">
                {{ form_label(form.freelance, 'Freelance', {'label_attr': {'class': 'form-label'}}) }}
                {{ form_widget(form.freelance, {'attr': {'class': 'form-check-input'}}) }}
                {{ form_errors(form.freelance) }}
            </div>
        </div>
    </div>
   <div class="row">
        <div class="col-md-2">
            <div class="mb-3">
                {{ form_label(form.dateCandidature, 'Date de candidature', {'label_attr': {'class': 'form-label'}}) }}
                {{ form_widget(form.dateCandidature, {'attr': {'class': 'form-control'}}) }}
                {{ form_errors(form.dateCandidature) }}
            </div>
        </div>
        <div class="col-md-6">
            <div class="mb-3">
                {{ form_label(form.description, 'Poste', {'label_attr': {'class': 'form-label'}}) }}
                {{ form_widget(form.description, {'attr': {'class': 'form-control'}}) }}
                {{ form_errors(form.description) }}
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <div class="mb-3">
                {{ form_label(form.entreprise, 'Entreprise', {'label_attr': {'class': 'form-label'}}) }}
                {{ form_widget(form.entreprise, {'attr': {'class': 'form-control'}}) }}
                {{ form_errors(form.entreprise) }}
            </div>
        </div>
        <div class="col-md-6">
            <div class="mb-3">
                {{ form_label(form.lieu, 'Lieu', {'label_attr': {'class': 'form-label'}}) }}
                {{ form_widget(form.lieu, {'attr': {'class': 'form-control'}}) }}
                {{ form_errors(form.lieu) }}
            </div>
        </div>
    </div>
     <div class="row align-items-center">
        <div class="col-md-10">
            <div class="mb-3">
                {{ form_label(form.url, 'Lien vers l\'offre', {'label_attr': {'class': 'form-label'}}) }}
                {{ form_widget(form.url, {'attr': {'class': 'form-control', 'placeholder': 'https://'}}) }}
                {{ form_errors(form.url) }}
            </div>
         </div>
        <div class="col-md-2">
            <input type="button" value="Importer depuis LinkedIn/Indeed" onclick="importFromURL(document.getElementById('offre_url').value)" class="btn btn-primary mt-2">
        </div>
    </div>
        
    <div class="mb-3">
        {{ form_label(form.contact, 'Contact', {'label_attr': {'class': 'form-label'}}) }}
        {{ form_widget(form.contact, {'attr': {'class': 'form-control', 'rows': '3'}}) }}
        {{ form_errors(form.contact) }}
    </div>
    
    <div class="row d-flex">
        <div class="col-md-4">
            <div class="mb-3">
                {{ form_label(form.reponse, 'Réponse', {'label_attr': {'class': 'form-label'}}) }}
                    {% for choice in form.reponse %}
                        <div class="form-check form-check-inline">
                            {{ form_widget(choice, {'attr': {'class': 'form-check-input'}}) }}
                            {{ form_label(choice, null, {'label_attr': {'class': 'form-check-label'}}) }}
                        </div>
                    {% endfor %}
                {{ form_errors(form.reponse) }}
            </div>
        </div>
        <div class="col-md-6">
            <div class="mb-3 row align-items-center">
                <div class="col-sm-2">
                    {{ form_label(form.reponse_at, 'Date ', {'label_attr': {'class': 'form-label mb-0'}}) }}
                </div>
                <div class="col-sm-8">
                    {{ form_widget(form.reponse_at, {'attr': {'class': 'form-control'}}) }}
                    {{ form_errors(form.reponse_at) }}
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-3">
            <div class="mb-3">
                {{ form_label(form.relance_at, 'Date de relance', {'label_attr': {'class': 'form-label'}}) }}
                {{ form_widget(form.relance_at, {'attr': {'class': 'form-control'}}) }}
                {{ form_errors(form.relance_at) }}
            </div>
        </div>
    </div>

    <div class="text-center">
        <button type="submit" class="btn btn-primary">{{ button_label|default('Enregistrer') }}</button>
    </div>

    
{{ form_end(form) }}

templates/offre/_tbody.html.twig
<tbody>
{% for offre in offres %}
    {% set 
        url = offre.url is not empty ? 
        '<a href="' ~ offre.url ~ '" target="_blank"><i class="fa-solid fa-link"></i></a>' 
        : ''  %}
    {% set type = offre.type == 'Informatique' ? '<i class="fa-solid fa-computer" title="Informatique"></i>' 
            : '<i class="fa-regular fa-face-frown-open" style="color:red" title="Autre"></i>'
    %}
    <tr class="{{ offre.reponse == 'NON' ? 'table-dark' : '' }}">
        <td>{{ offre.id }}</td>
        <td>{{ offre.dateCandidature ? offre.dateCandidature|date('d-m-Y') : '' }}</td>
        <td>{{ offre.entreprise | raw  }}</td>
        <td>{{ offre.lieu | raw  }}</td>
        <td>{{ url | raw }}
        {% if offre.isUrlValid() is not same as(false) %}
                    <span class="text-danger">Invalide</span>
                {% endif %}</td>
        <td>{% if offre.getSiteNameFromUrl() %}
       {{ offre.getSiteNameFromUrl() }}
        {% endif %}</td>
        <td>{{ offre.contact }}</td>
        <td>{{ offre.reponse != 'ATTEN' ? offre.reponse : ''  }} {{ offre.reponseAt ? offre.reponseAt|date('d-m-Y') : '' }}</td>
        <td>{{ offre.relanceAt ? offre.relanceAt|date('d-m-Y') : '' }}</td>
        <td>
            <span class="d-flex align-items-center gap-2">
                {{ offre.freelance == 'Yes' ? '<i class="fa-solid fa-house-laptop" title="Freelance"></i>' : '' }} 
                {{ type | raw }}
            </span>
        </td>
        <td>
            <a href="{{ path('app_offre_edit', {'id': offre.id}) }}" alt="MAJ"><i class="fa-solid fa-pen" title="MAJ"></i></a>
        </td>
    </tr>
{% else %}
    <tr>
        <td colspan="13">no records found</td>
    </tr>
{% endfor %}
</tbody>

templates/offre/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit candidature n°{% endblock %}

{% block body %}
    <div class="container mt-4">
        <h1 class="mb-4">Edition de la candidature n°{{ offre.id }}</h1>

        {{ include('offre/_form.html.twig', {'button_label': 'Mise à jour'}) }}

        <a href="{{ path('app_home') }}" class="btn btn-primary">Retour</a>

        {{ include('offre/_delete_form.html.twig') }}
    </div>
{% endblock %}

templates/offre/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Offres dashboard{% endblock %}

{% block body %}
<div class="container">
    <h1 class="pb-2 border-bottom d-flex justify-content-between">Dashboard - {{ offres|length }} candidatures

    <a href="{{ path('app_home', {'reponse' : 'ATT'}) }}"  class="btn btn-light btn-sm">Candidatures en attente</a>
    <a href="{{ path('app_home', {'reponse' : 'NON'}) }}"  class="btn btn-secondary btn-sm">Candidatures refusée</a>

    <a href="{{ path('app_home', {'checkUrls' : '1'}) }}" class="btn btn-danger btn-sm">Vérification URL</a>
    {% include "offre/_find.html.twig" %}
    <a href="{{ path('app_offre_new') }}"><i class="fas fa-plus"></i></a>
    </h1>

    <table class="table table-striped sortable" id="myTable">
        <thead>
            <tr >
                <th scope="col">Id</th>
                <th scope="col">DateCandidature</th>
                <th scope="col">Entreprise</th>
                <th scope="col">Lieu</th>
                <th scope="col" class="unsortable">Url</th>
                <th scope="col">Site</th>
                <th scope="col">Contact</th>
                <th scope="col">Reponse</th>
                <th scope="col">Relance</th>
                <th scope="col"></th>
                <th scope="col" class="unsortable">actions</th>
            </tr>
        </thead>
        {% include "offre/_tbody.html.twig" %}
    </table>

</div>

{% endblock %}
{% block javascripts %}
    {{ parent() }}
    {{ encore_entry_script_tags("sorttable") }}

{% endblock %}

templates/offre/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Offre{% endblock %}

{% block body %}
    <div class="container mt-4">
        <h1 class="mb-4">Nouvelle candidature</h1>

        {{ include('offre/_form.html.twig') }}

        <a href="{{ path('app_home') }}" class="btn btn-primary">Retour</a>
    </div>
{% endblock %}